#!/bin/sh /etc/rc.common

START=96
STOP=09
USE_PROCD=1

NAME="h340raidmon"
PROG="/usr/bin/h340raidmon"

start_service()
{
    # h340raidmon requires the LED daemon.
    [ -x /usr/bin/h340led ] || {
        logger -t "$NAME" "h340led is not installed"
        return 1
    }

    procd_open_instance
    procd_set_param command "$PROG"
    procd_set_param respawn
    procd_set_param stdout 1
    procd_set_param stderr 1
    procd_close_instance
}
