#!/bin/sh /etc/rc.common

START=95
STOP=10
USE_PROCD=1

NAME="h340led"
PROG="/usr/bin/h340led"

start_service()
{
    procd_open_instance
    procd_set_param command "$PROG" daemon
    procd_set_param respawn
    procd_set_param stdout 1
    procd_set_param stderr 1
    procd_close_instance
}
